services:
  rabbitmq:
    image: rabbitmq:4.0.3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672 # AMQP
      - 15672:15672 # Management
      - 15692:15692 # Prometeus
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_prometheus && rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 3s
      retries: 5
